# Git_Zipper_Uploader_AzureDevOps pipeline

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
# Check for Git
- script: git --version
  displayName: 'Check for Git'

# Clone Repository
- script: git clone https://github.com/QuarkLabs/i-have-a-theory
  displayName: 'Clone Repository'
