# Git_Zipper_Uploader_AzureDevOps pipeline

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

# Variables
variables:
  owner: wasabeef
  repository: awesome-android-ui

steps:
# Check for Git
- script: git --version
  displayName: 'Check for Git'

# Clone Repository & Verify Clone
- script: |
    git clone https://github.com/$(owner)/$(repository)
    echo 
    echo Repository Contents
    echo --------------------------------------------------------
    ls -all $(repository)
  displayName: 'Clone Repository'

# Check for Zip
- script: zip --version
  displayName: 'Check for Zip'

# Compress Repository & Verify Compress
- script: |
    zip -r $(repository).zip $(repository) 
    echo 
    echo Current Directory Contents
    echo --------------------------------------------------------
    ls
  displayName: 'Zip Repository'

# Upload Repository Zip File
- task: FtpUpload@1
  displayName: 'FTP Upload Repository Zip File'
  inputs:
    credentialsOption: inputs
    serverUrl: 'ftp://192.254.233.216'
    username: 'root@alaneesgroup.com'
    password: 9895204814
    # TODO : Add option for file instead of directory
    rootDirectory: '.'
    remoteDirectory: '/azure_devops/git_zipper_uploader'
    filePatterns: '$(repository).zip'