parameters:
  - name: vmImage
    displayName: Pool VM Image
    type: string
    default: windows-latest
    values:
      - windows-latest
      - ubuntu-latest

trigger: none

jobs:
  - job: "Upload_Zip_of_Git_Repository"

    pool:
      vmImage: ${{parameters.vmImage}}

    # Variables
    variables:
      hosting_provider: github.com
      owner: odoo
      repository: odoo

    steps:
      - checkout: self
        fetchDepth: "1"

      # Check for Git
      - script: git --version
        displayName: "Check for Git"

      # Clone Repository & Verify Clone
      - script: |
          git clone https://$(hosting_provider)/$(owner)/$(repository).git
          echo
          echo Repository Contents
          echo --------------------------------------------------------
          ls -all $(repository)
        displayName: "Clone Repository"

      # Check for Zip
      - ${{if eq(parameters.vmImage, 'windows-latest')}}:
        - script: 7z --version
          displayName: "Check for 7Zip"

      - ${{if eq(parameters.vmImage, 'ubuntu-latest')}}:
        - script: zip --version
          displayName: "Check for Zip"

      # Compress Repository & Verify Compress
      - ${{if eq(parameters.vmImage, 'windows-latest')}}:
        - script: |
            7z a -tzip $(repository).zip $(repository)
            echo
            echo Current Directory Contents
            echo --------------------------------------------------------
            dir
          displayName: "Zip Repository"

      - ${{if eq(parameters.vmImage, 'ubuntu-latest')}}:
        - script: |
            zip -r $(repository).zip $(repository)
            echo
            echo Current Directory Contents
            echo --------------------------------------------------------
            ls
          displayName: "Zip Repository"

      - publish: "$(repository).zip"
        artifact: "$(owner)_$(repository)_${{parameters.vmImage}}"
