# Git_Zipper_Uploader_AzureDevOps pipeline

trigger:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'

# Variables
variables:
  owner: gatsbyjs
  repository: gatsby
  
  # Secret Variables
  MAPPED_FTP_HOST: $(FTP_HOST)
  MAPPED_FTP_USER: $(FTP_USER)
  MAPPED_FTP_PWD: $(FTP_PWD)

steps:
# Check for Git
- script: git --version
  displayName: 'Check for Git'

# Clone Repository & Verify Clone
- script: |
    git clone https://github.com/$(owner)/$(repository)
    echo 
    echo Repository Contents
    echo --------------------------------------------------------
    ls -all $(repository)
  displayName: 'Clone Repository'

# Check for Zip
- script: zip --version
  displayName: 'Check for Zip'

# Compress Repository & Verify Compress
- script: |
    zip -r $(repository).zip $(repository) 
    echo 
    echo Current Directory Contents
    echo --------------------------------------------------------
    ls
  displayName: 'Zip Repository'

# Upload Repository Zip File
- task: FtpUpload@1
  displayName: 'FTP Upload Repository Zip File'
  inputs:
    credentialsOption: inputs
    serverUrl: 'ftp://$(MAPPED_FTP_HOST)'
    username: '$(MAPPED_FTP_USER)'
    password: $(MAPPED_FTP_PWD)
    # TODO : Add option for file instead of directory
    rootDirectory: '.'
    remoteDirectory: '/azure_devops/git_zipper_uploader'
    filePatterns: '$(repository).zip'
