# Git_Zipper_Uploader_AzureDevOps pipeline

trigger:
- feature/zip

pool:
  vmImage: 'ubuntu-latest'

steps:
# Check for Git
- script: git --version
  displayName: 'Check for Git'

# Clone Repository & Verify Clone
- script: |
    git clone https://github.com/QuarkLabs/i-have-a-theory
    echo 
    echo Repository Contents
    echo --------------------------------------------------------
    ls i-have-a-theory
  displayName: 'Clone Repository'

# Check for Zip
- script: zip --version
  displayName: 'Check for Zip'

# Compress Repository & Verify Compress
- script: |
    zip -r i-have-a-theory.zip i-have-a-theory 
    echo 
    echo Current Directory Contents
    echo --------------------------------------------------------
    ls
  displayName: 'Zip Repository'