parameters:
  - name: vmImage
    displayName: Pool VM Image
    type: string
    default: windows-latest
    values:
      - windows-latest
      - ubuntu-latest

  - name: hostingProvider
    displayName: Hosting Provider
    type: string
    default: github.com
    values:
      - github.com
      - gitlab.com

  - name: repositoryOwner
    displayName: Repository Owner
    type: string
    default: phpmyadmin

  - name: repositoryName
    displayName: Repository Name
    type: string
    default: phpmyadmin

trigger: none

jobs:
  - job: "Upload_Zip_of_Git_Repository"

    pool:
      vmImage: ${{parameters.vmImage}}

    steps:
      - checkout: self
        fetchDepth: "1"

      # Check for Git
      - script: git --version
        displayName: "Check for Git"

      # Clone Repository & Verify Clone
      - script: |
          git clone https://$(parameters.hostingProvider)/${{parameters.repositoryOwner}}/$(parameters.repositoryName).git
          echo
          echo Repository Contents
          echo --------------------------------------------------------
          ls -all $(repository)
        displayName: "Clone Repository"

      # Check for Zip
      - ${{if eq(parameters.vmImage, 'windows-latest')}}:
        - script: 7z i
          displayName: "Check for 7Zip"

      - ${{if eq(parameters.vmImage, 'ubuntu-latest')}}:
        - script: zip --version
          displayName: "Check for Zip"

      # Compress Repository & Verify Compress
      - ${{if eq(parameters.vmImage, 'windows-latest')}}:
        - script: |
            7z a -tzip ${{parameters.repositoryOwner}}_$(parameters.repositoryName)_${{parameters.vmImage}}.zip $(parameters.repositoryName)
            echo
            echo Current Directory Contents
            echo --------------------------------------------------------
            dir
          displayName: "Zip Repository"

      - ${{if eq(parameters.vmImage, 'ubuntu-latest')}}:
        - script: |
            zip -r ${{parameters.repositoryOwner}}_$(parameters.repositoryName)_${{parameters.vmImage}}.zip $(parameters.repositoryName)
            echo
            echo Current Directory Contents
            echo --------------------------------------------------------
            ls
          displayName: "Zip Repository"

      - publish: "${{parameters.repositoryOwner}}_$(parameters.repositoryName)_${{parameters.vmImage}}.zip"
        artifact: "$(parameters.repositoryOwner)_$(parameters.repositoryName)_${{parameters.vmImage}}"
